Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -7,6 +7,7 @@ on:
 
 env:
   FOUNDRY_PROFILE: ci
+  
 
 jobs:
   check:
@@ -41,3 +42,8 @@ jobs:
         run: |
           forge test -vvv
         id: test
+
+      - name: Debug Forge build
+        run: |
+          forge build
+        --sizes || (echo "Build failed. Checking for issues..." && forge diagnose)
